### ISSUE TITLE
[BUG] - transform task fails when using BigQuery GAP_FILL function in sql code

### ISSUE THREAD

**Issue by jwazne** [starlake-ai/starlake#1142]
## Description
The use of the **BigQuery GAP_FILL function** in SQL code gives a JSqlParser error when running starlake transform command.

## Expected behavior
Successful loading of the target table

## Current Behavior
Transform task fails with the following error :
```
Error raised : 
ERROR SchemaHandler: net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
```
N.B. : see full stack trace below

## Steps to reproduce
1/ Create a `metadata/transform/montest/zetest.sql` file with the following content : 
```sql
with raw_data as (
    select timestamp('2024-12-01') zetime
    union all 
    select timestamp('2024-12-04')
  )
select zetime from GAP_FILL(
  TABLE raw_data,
  ts_column => 'zetime',
  bucket_width => INTERVAL 4 HOUR
)
```

2/ Run the transform command :
```sh
starlake transform --name=montest.zetest
```

## Workaround
Use PRESQL, SQL and POSTSQL as follow (N.B. : replace <dataset_id> by a valid value):
```sql
create or replace view <dataset_id>.zeview as (
with raw_data as (
    select timestamp('2024-12-01') zetime
    union all 
    select timestamp('2024-12-04')
  )
select zetime from GAP_FILL(
  TABLE raw_data,
  ts_column => 'zetime',
  bucket_width => INTERVAL 4 HOUR
)
)

-- SQL
select zetime from <dataset_id>.zeview

-- POSTSQL
DROP view <dataset_id>.zeview
```

## Full stack trace
```
24/12/05 17:35:24 ERROR SQLUtils$: Failed to parse with raw_data as (
select timestamp('2024-12-01') zetime
union all
select timestamp('2024-12-04')
)
select zetime from GAP_FILL(
TABLE raw_data,
ts_column => 'zetime',
bucket_width => INTERVAL 4 HOUR
)
ORDER BY zetime asc
24/12/05 17:35:24 ERROR SchemaHandler: net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 6, column 28.

Was expecting one of:

    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:352)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:125)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:91)
	at ai.starlake.sql.SQLUtils$.jsqlParse(SQLUtils.scala:144)
	at ai.starlake.sql.SQLUtils$.extractCTENames(SQLUtils.scala:128)
	at ai.starlake.sql.SQLUtils$.buildSingleSQLQueryForRegex(SQLUtils.scala:198)
	at ai.starlake.sql.SQLUtils$.substituteRefInSQLSelect(SQLUtils.scala:163)
	at ai.starlake.schema.handlers.SchemaHandler.substituteRefTaskMainSQL(SchemaHandler.scala:1558)
	at ai.starlake.schema.handlers.SchemaHandler.$anonfun$transpileAndSubstitute$1(SchemaHandler.scala:1580)
	at scala.util.Try$.apply(Try.scala:217)
	at ai.starlake.schema.handlers.SchemaHandler.transpileAndSubstitute(SchemaHandler.scala:1577)
	at ai.starlake.job.transform.AutoTask.buildAllSQLQueries(AutoTask.scala:131)
	at ai.starlake.job.transform.BigQueryAutoTask.runBQ(BigQueryAutoTask.scala:172)
	at ai.starlake.job.transform.BigQueryAutoTask.run(BigQueryAutoTask.scala:381)
	at ai.starlake.workflow.IngestionWorkflow.transform(IngestionWorkflow.scala:1176)
	at ai.starlake.workflow.IngestionWorkflow.autoJob(IngestionWorkflow.scala:1157)
	at ai.starlake.job.transform.TransformCmd.run(TransformCmd.scala:100)
	at ai.starlake.job.transform.TransformCmd.run$(TransformCmd.scala:94)
	at ai.starlake.job.transform.TransformCmd$.run(TransformCmd.scala:106)
	at ai.starlake.job.transform.TransformCmd$.run(TransformCmd.scala:106)
	at ai.starlake.job.Cmd.run(Cmd.scala:19)
	at ai.starlake.job.Cmd.run$(Cmd.scala:14)
	at ai.starlake.job.transform.TransformCmd$.run(TransformCmd.scala:106)
	at ai.starlake.job.Main.run(Main.scala:286)
	at ai.starlake.job.Main.$anonfun$run$1(Main.scala:187)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at ai.starlake.job.Main.run(Main.scala:184)
	at ai.starlake.job.Main$.main(Main.scala:70)
	at ai.starlake.job.Main.main(Main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.util.concurrent.ExecutionException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 6, column 28.

Was expecting one of:

    <EOF>
    <ST_SEMICOLON>

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:345)
	... 42 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 6, column 28.

Was expecting one of:

    <EOF>
    <ST_SEMICOLON>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:45749)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:45570)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:345)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:341)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:338)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by hayssams** [comment]
Thanks @jwazne 
Just reported in JSQLParser 
https://github.com/JSQLParser/JSqlParser/issues/2120

**Comment by jwazne** [comment]
After testing by replacing TABLE <table_name> by a select query, it works :

The following query works : 

```sql
with raw_data as (
    select timestamp('2024-12-01') zetime
    union all 
    select timestamp('2024-12-04')
  )
select zetime from GAP_FILL(
  (select * from raw_data),
  ts_column => 'zetime',
  bucket_width => INTERVAL 4 HOUR
)
ORDER BY zetime asc
```

**Comment by hayssams** [comment]
Added support for TABLE in GAP_FILL, APPENDS and CHANGES
