### ISSUE TITLE
[BUG] - Starlake transform commands fail with MotherDuck as target DWH

### ISSUE THREAD

**Issue by jwazne** [starlake-ai/starlake#1168]
## Description
Starlake transform commands fail with MotherDuck as target DWH

## Expected behavior
Transform goes successfully without errors.

## Current Behavior
Transform fails with following exception (see full stacktrace below) : 
```
Exception in thread "main" java.sql.SQLException: Permission Error: Loading external extensions is disabled through configuration
```

## Steps to reproduce
Create the following `transform/montest/zetest.sql` file:
```SQL
select 1+2 as trois
```
Run the following command:
```
$HOME/starlake/starlake transform --name=montest.zetest
```

## Context
N.B. : The same transform works well with **Starlake version 1.2.0**

## Possible cause
The culprit may be the duckdb driver used by Starlake distribution.
For the Starlake version 1.3.1-SNAPSHOT, duckdb driver v1.1.3 is used :  [project/Versions.scala](https://github.com/starlake-ai/starlake/blob/0c2388ae8b44d9d9ea9a108ef21c7ced0ceb0ea7/project/Versions.scala#L40)
For the Starlake version 1.2.0, duckdb driver v1.0.0 is used :  https://github.com/starlake-ai/starlake/blob/v1.2.0/project/Versions.scala

The error message indicates issue with the database configuration.
cf. https://duckdb.org/docs/configuration/overview

However on the target MotherDuck database, the **enable_external_access** configuration is well enabled:
<img width="688" alt="image" src="https://github.com/user-attachments/assets/dfcf36be-c62d-49f7-831e-6cc644851014" />

# Full stacktrace
```
Exception in thread "main" java.sql.SQLException: Permission Error: Loading external extensions is disabled through configuration
	at org.duckdb.DuckDBNative.duckdb_jdbc_startup(Native Method)
	at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:51)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:41)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at ai.starlake.extract.JdbcDbUtils$StarlakeConnectionPool$.getConnection(JdbcDbUtils.scala:69)
	at ai.starlake.extract.JdbcDbUtils$.$anonfun$withJDBCConnection$1(JdbcDbUtils.scala:131)
	at scala.util.Try$.apply(Try.scala:217)
	at ai.starlake.extract.JdbcDbUtils$.withJDBCConnection(JdbcDbUtils.scala:131)
	at ai.starlake.job.transform.JdbcAutoTask.tableExists(JdbcAutoTask.scala:65)
	at ai.starlake.job.transform.AutoTask.$anonfun$buildAllSQLQueries$4(AutoTask.scala:153)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.Option.getOrElse(Option.scala:201)
	at ai.starlake.job.transform.AutoTask.buildAllSQLQueries(AutoTask.scala:153)
	at ai.starlake.job.transform.JdbcAutoTask.$anonfun$runJDBC$2(JdbcAutoTask.scala:142)
	at scala.util.Try$.apply(Try.scala:217)
	at ai.starlake.job.transform.JdbcAutoTask.runJDBC(JdbcAutoTask.scala:139)
	at ai.starlake.job.transform.JdbcAutoTask.run(JdbcAutoTask.scala:60)
	at ai.starlake.workflow.IngestionWorkflow.transform(IngestionWorkflow.scala:1192)
	at ai.starlake.workflow.IngestionWorkflow.autoJob(IngestionWorkflow.scala:1157)
	at ai.starlake.job.transform.TransformCmd.run(TransformCmd.scala:100)
	at ai.starlake.job.transform.TransformCmd.run$(TransformCmd.scala:94)
	at ai.starlake.job.transform.TransformCmd$.run(TransformCmd.scala:106)
	at ai.starlake.job.transform.TransformCmd$.run(TransformCmd.scala:106)
	at ai.starlake.job.Cmd.run(Cmd.scala:19)
	at ai.starlake.job.Cmd.run$(Cmd.scala:14)
	at ai.starlake.job.transform.TransformCmd$.run(TransformCmd.scala:106)
	at ai.starlake.job.Main.run(Main.scala:286)
	at ai.starlake.job.Main.$anonfun$run$1(Main.scala:187)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at ai.starlake.job.Main.run(Main.scala:184)
	at ai.starlake.job.Main$.main(Main.scala:70)
	at ai.starlake.job.Main.main(Main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by jwazne** [comment]
More context: 

This is the original mail I've received from MotherDuck support and that motivates me to upgrade my Starlake version from 1.2.0 to 1.3.1-SNAPSHOT: 

> You are receiving this message because in the past 14 days, you have connected to the MotherDuck service using a version of DuckDB that is approaching end-of-life with MotherDuck.
> 
> After January 15, 2025, MotherDuck will no longer support connections from DuckDB client versions 0.10.2, 0.10.3, and 1.0.0. Please expect that after this date, connection attempts from these DuckDB client versions to MotherDuck will be unsuccessful.
> 
> You must upgrade all DuckDB clients used personally or in automated processes to at least DuckDB 1.1.0 before January 15, 2025 to prevent failures in scheduled jobs or services connected to your MotherDuck databases.

**Comment by hayssams** [comment]
@jwazne 
Thanks for submitting this issue. To safeguard against any access to the filesystem, we've explicitly disabled external_Access which seems to be required by motherduck even when there is none.
We've just made external access always available on motherduck and now user configurable on other duckdb databases using the SL_DUCKDB_ENABLE_EXTERNAL_ACCESS boolean env.
For your specific use-case, all you have to do to make it work is to download the new snapshot

**Comment by hayssams** [comment]
solved
