### ISSUE TITLE
[BUG] - Empty test load folder throws an exception that is not user friendly

### ISSUE THREAD

**Issue by tiboun** [starlake-ai/starlake#890]
create a structure test but don't add any file in it. Launch load test, an exception is thrown:

```
java.sql.SQLException: java.sql.SQLException: Invalid Input Error: No statements to execute.
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:122)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:196)
	at ai.starlake.tests.StarlakeTestData.load(StarlakeTests.scala:56)
	at ai.starlake.tests.StarlakeTest.load(StarlakeTests.scala:32)
	at ai.starlake.tests.StarlakeTestData$.$anonfun$run$5(StarlakeTests.scala:279)
	at ai.starlake.tests.StarlakeTestData$.$anonfun$run$5$adapted(StarlakeTests.scala:274)
	at ai.starlake.utils.Utils$.withResources(Utils.scala:74)
	at ai.starlake.tests.StarlakeTestData$.$anonfun$run$3(StarlakeTests.scala:274)
	at scala.collection.immutable.List.map(List.scala:297)
	at ai.starlake.tests.StarlakeTestData$.$anonfun$run$2(StarlakeTests.scala:264)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at ai.starlake.tests.StarlakeTestData$.$anonfun$run$1(StarlakeTests.scala:261)
	at scala.collection.immutable.List.flatMap(List.scala:366)
```

**Comment by hayssams** [comment]
Fixed. 
Empty tests are now ignored
